# Generated by Django 4.1.7 on 2023-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appdemo", "0002_hotel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
